/**
 * POST /simulate route
 *
 * Provides a first-class demo path. Accepts an optional scenario name, loads
 * the corresponding bundled fixture log, injects synthetic metadata, and runs
 * the payload through the same ingestBuild + job-queue pipeline as a real
 * webhook — so the full truncation and LLM analysis path is exercised.
 *
 * Requirements: 2.1, 2.2, 2.3, 2.4
 */

import { Router, type Request, type Response } from "express";
import { readFileSync } from "fs";
import { join } from "path";
import { ingestBuild, IngestValidationError } from "../services/ingestBuild.js";
import { verifyToken } from "../auth/authService.js";
import type { SimulationScenario } from "../types.js";

const router = Router();

// ── Constants ─────────────────────────────────────────────────────────────────

const VALID_SCENARIOS: ReadonlySet<SimulationScenario> = new Set([
  "test-failure",
  "dependency-error",
  "docker-build-failure",
  "env-var-missing",
  "timeout",
  "lint-error",
]);

const DEFAULT_SCENARIO: SimulationScenario = "test-failure";

/**
 * Deterministic 40-char hex commitSha per scenario.
 * Generated by padding a fixed prefix unique to each scenario name so that
 * repeated simulate calls for the same scenario always use the same SHA,
 * making logs easy to correlate in demos.
 */
const SCENARIO_COMMIT_SHAS: Record<SimulationScenario, string> = {
  "test-failure":          "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
  "dependency-error":      "b2c3d4e5f6b2c3d4e5f6b2c3d4e5f6b2c3d4e5f6",
  "docker-build-failure":  "c3d4e5f6c3d4e5f6c3d4e5f6c3d4e5f6c3d4e5f6",
  "env-var-missing":       "d4e5f6d4e5f6d4e5f6d4e5f6d4e5f6d4e5f6d4e5",
  "timeout":               "e5f6e5f6e5f6e5f6e5f6e5f6e5f6e5f6e5f6e5f6",
  "lint-error":            "f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6",
};

// Resolve the fixtures directory relative to this source file so it works
// regardless of the current working directory when the server is started.
const FIXTURES_DIR = join(__dirname, "../../fixtures");

// ── Helper ────────────────────────────────────────────────────────────────────

/** Synchronously reads the fixture log for a given scenario. */
function loadFixtureLog(scenario: SimulationScenario): string {
  const filePath = join(FIXTURES_DIR, `${scenario}.log`);
  return readFileSync(filePath, "utf-8");
}

// ── Route ─────────────────────────────────────────────────────────────────────

/**
 * POST /simulate
 *
 * Body (all fields optional):
 *   { scenario?: SimulationScenario }
 *
 * Response 202:
 *   { id: string; scenario: SimulationScenario; status: "pending" }
 *
 * Response 400:
 *   { error: string; details: string[] }
 */
router.post("/", async (req: Request, res: Response): Promise<void> => {
  const rawScenario: unknown = req.body?.scenario;

  // ── Default + validation ──────────────────────────────────────────────────
  let scenario: SimulationScenario;

  if (rawScenario === undefined || rawScenario === null || rawScenario === "") {
    scenario = DEFAULT_SCENARIO;
  } else if (typeof rawScenario === "string" && VALID_SCENARIOS.has(rawScenario as SimulationScenario)) {
    scenario = rawScenario as SimulationScenario;
  } else {
    res.status(400).json({
      error: "Invalid scenario",
      details: [
        `scenario must be one of: ${[...VALID_SCENARIOS].join(", ")} — got "${rawScenario}"`,
      ],
    });
    return;
  }

  // ── Resolve userId from auth cookie ──────────────────────────────────────
  const token: string | undefined = req.cookies?.auth_token;
  let userId: string | null = null;
  if (token) {
    const user = verifyToken(token);
    if (user) {
      userId = user.userId;
    }
  }

  // ── Load fixture ──────────────────────────────────────────────────────────
  let log: string;
  try {
    log = loadFixtureLog(scenario);
  } catch (err) {
    console.error(`[simulate] Failed to load fixture for scenario "${scenario}":`, err);
    res.status(500).json({ error: "Internal server error" });
    return;
  }

  // ── Synthetic metadata ────────────────────────────────────────────────────
  // Generate a unique commitSha per user to avoid UNIQUE constraint violations
  // when multiple users simulate the same scenario.
  const baseCommitSha = SCENARIO_COMMIT_SHAS[scenario];
  const commitSha = userId
    ? (baseCommitSha.slice(0, 32) + Buffer.from(userId).toString("hex").slice(0, 8)).slice(0, 40)
    : baseCommitSha;

  const payload = {
    log,
    repoName: "demo/repo",
    jobName: "CI / simulate",
    commitSha,
    branch: "main",
  };

  // ── Ingest (same path as real webhook) ────────────────────────────────────
  try {
    const record = await ingestBuild(payload, "simulate", userId);

    res.status(202).json({
      id: record.id,
      scenario,
      status: "pending",
    });
  } catch (err) {
    if (err instanceof IngestValidationError) {
      // Unexpected — synthetic payload should always be valid, but guard anyway
      res.status(400).json({
        error: err.message,
        details: err.details,
      });
    } else {
      console.error("[simulate] Unexpected error during ingestBuild:", err);
      res.status(500).json({ error: "Internal server error" });
    }
  }
});

export default router;
